### ISSUE TITLE
Support for Arrow Functions

### ISSUE THREAD

**Issue by benneq** [bluetech/ng-annotate-patched#12]
I'm using TypeScript with `ng-annotate-patched` (version: 1.7.0).

It's working fine when using `target: "es5"`, because then all arrow functions become normal functions **before** `ng-annotate` does its thing.

When using `target: "es6"`, it breaks.

When changing the code from:
```
myModule.run(($injector) => {'ngInject'; ... })
```
to:
```
myModule.run(function($injector) {'ngInject'; ... })
```
it will work again. Though I guess that `ng-annotate-patch` can't handle arrow functions ❓ 

Same applies for provider's `$get` function:
```
class MyProvider implements ng.IServiceProvider {
	public defaultTitle: Array<string> = [];
	public separator: string = ' ';

	public $get($rootScope: ng.IRootScopeService, $window: ng.IWindowService, $interpolate: ng.IInterpolateService) => {'ngInject';
		//...
	}
}
```
This won't work when switching compiler output to `es6`.

Or is there some plugin option I didn't see?

**Comment by bluetech** [comment]
> Though I guess that ng-annotate-patch can't handle arrow functions?

That's probably true. To explain:

I use this project with TypeScript as well, with target: "es5" and modules: "es2015". The original ng-annotate did not work well with modules: "es2015" (`import`/`export` etc.), so I forked it and added support for these. But I did not add full support for all ES6 forms, so ES6 classes, arrow functions and similar are not recognized (it's not needed with target: "es5").

There is an open PR for ES6 classes (#5), but not for arrows. It is most likely easier to add support for arrow functions, though, since they are not that different from `function()`s. If someone likes to try, that'd be great.
