### ISSUE TITLE
Support for typescript 

### ISSUE THREAD

**Issue by mariuszbeltowski** [bluetech/ng-annotate-patched#7]
Right now it's not possible to annotate typescript files becuase of parse error.

`ng-annotate-patched -a src/angularjs/app/login/login.ts`
```
error: couldn't process source due to parse error
Unexpected token (11:26)
```
Which is exactly the line with TS type: `function LoginController(): void {}`

Motivation:
I'm in the middle of the AngularJS app upgrade and I would like to switch for angular-cli from webpack, which unfortunately does not support the ng-annotate. The AngularJS code in my app is no longer developed (new features are developed in Angular). So the idea which came to my mind it to parse all the angularjs typescript files with `ng-annotate-patched` and commit the changes with explicit annotations. Unfortunately, `ng-annotate-patched` does not support syntax of the typescript language.

Do you know how this could be easily fixed? or maybe there is an existing fork for TS? 
Thank you in advance @bluetech

**Comment by bluetech** [comment]
ng-annotate uses [acorn](https://github.com/acornjs/acorn) to parse JS. acorn doesn't have a typescript plugin as far as I can see.

A possible avenue is to replace acorn with another parser, most likely babel's parser [babylon](https://github.com/babel/babel/tree/master/packages/babylon), which supports TS syntax. According to its README, it should be compatible if you enable the `estree` plugin. I will not be doing it myself, but maybe someone else wants to try.

Another thing you might try is using the ng-annotate [babel plugin](https://github.com/schmod/babel-plugin-angularjs-annotate) and see if it's possible to make it work with TS syntax (now that babel itself supports TS syntax). Since you are aiming for a one-time operation, something a little hacky to get the job done might be fine.

**Comment by mariuszbeltowski** [comment]
I've also notice that acorn does not support TS and wasn't able to find any fork which could do that.

Anyway, I've created a small python script which annotated all the constructor and turned on the `strictDi` for AngularJS bootstrapping.

Thank you for your help, we can close it :)
